apiVersion: v1
kind: Service
metadata:
  name: selenium-srv
  labels:
    app: selenium-srv
spec:
  selector:
    app: selenium-hub
  ports:
  - name: http
    port: 80
    targetPort: 4444
  type: LoadBalancer
